"""updatÑe

Revision ID: f3d1a8bbdbc9
Revises: 66c20e8ccb30
Create Date: 2026-03-20 12:53:37.667338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d1a8bbdbc9'
down_revision: Union[str, Sequence[str], None] = '66c20e8ccb30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('text', sa.String(length=500), nullable=False))
    op.add_column('posts', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.add_column('posts', sa.Column('image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image')
    op.drop_column('posts', 'is_published')
    op.drop_column('posts', 'text')
    # ### end Alembic commands ###
